atom_elements(c1,carbon,[c2,c7]).
atom_elements(c2,carbon,[c1,c3,h1]).
atom_elements(c3,carbon,[c2,c4,c8]).
atom_elements(c4,carbon,[c3,c5,h2]).
atom_elements(c5,carbon,[c1,c4,c9]).
atom_elements(c7,carbon,[c1,h4,h5,h6]).
atom_elements(c8,carbon,[c3,h7,h8,h9]).
atom_elements(c9,carbon,[c5,h10,h11,h12]).

atom_elements(h1,hydrogen,[c2]).
atom_elements(h2,hydrogen,[c4]).
atom_elements(h4,hydrogen,[c7]).
atom_elements(h5,hydrogen,[c7]).
atom_elements(h6,hydrogen,[c7]).
atom_elements(h7,hydrogen,[c8]).
atom_elements(h8,hydrogen,[c8]).
atom_elements(h9,hydrogen,[c8]).
atom_elements(h10,hydrogen,[c9]).
atom_elements(h11,hydrogen,[c9]).
atom_elements(h12,hydrogen,[c9]).
